apiVersion: apps/v1
kind: Deployment
metadata:
  name: Crud-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Crud-frontend
  template:
    metadata:
      labels:
        app: Crud-frontend
    spec:
      containers:
      - name: frontend
        image: crud-frontend
        ports:
        - containerPort: 3000


---
apiVersion: v1
kind: Service
metadata:
  name: crud-frontend
spec:
  type: NodePort
  selector:
    app: Crud-frontend
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 3000