apiVersion: v1
kind: Service
metadata:
  name: mern-crud-service
  namespace: mern-crud-ns
spec:
  selector:
    app: mern-crud-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer